# Generated by Django 3.1 on 2020-08-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistasymodelos', '0003_auto_20200824_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidos',
            name='nombres_equipos',
        ),
    ]
