# Generated by Django 3.1 on 2020-08-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vistasymodelos', '0004_remove_partidos_nombres_equipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_local', models.CharField(max_length=10)),
                ('resultado_visitante', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Posciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistasymodelos.equipo')),
            ],
        ),
    ]
