# Generated by Django 3.1 on 2020-08-24 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vistasymodelos', '0005_posciones_resultados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultados',
        ),
        migrations.AddField(
            model_name='partidos',
            name='resultado_local',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partidos',
            name='resultado_visitante',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
