# Generated by Django 3.1 on 2020-08-24 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vistasymodelos', '0007_auto_20200824_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidos',
            name='id',
        ),
        migrations.AddField(
            model_name='partidos',
            name='identificador',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
