# Generated by Django 3.1 on 2020-08-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistasymodelos', '0008_auto_20200824_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidos',
            name='identificador',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
