# Generated by Django 3.1 on 2020-08-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistasymodelos', '0010_auto_20200824_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidos',
            old_name='resultado_local',
            new_name='resul_local',
        ),
        migrations.RenameField(
            model_name='partidos',
            old_name='resultado_visitante',
            new_name='resul_visitante',
        ),
    ]
