# Generated by Django 3.1 on 2020-08-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistasymodelos', '0012_auto_20200824_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posciones',
            new_name='Posiciones',
        ),
    ]
