# Generated by Django 3.1 on 2020-08-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.CharField(max_length=50)),
                ('visitante', models.CharField(max_length=40)),
                ('local', models.CharField(max_length=40)),
                ('estadio_jugaran', models.CharField(max_length=50)),
                ('resultado_local', models.CharField(max_length=10, null=True)),
                ('resultado_visitante', models.CharField(max_length=10, null=True)),
                ('fecha', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=20)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistaymodelo.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Posiciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistaymodelo.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='estadio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistaymodelo.estadio'),
        ),
    ]
