# Generated by Django 3.1 on 2020-08-25 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vistaymodelo', '0002_auto_20200825_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posiciones',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistaymodelo.equipo'),
        ),
    ]
